### ISSUE TITLE
Zotero integration

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#1]
# Target fields from item list (collection)
- [ ] Title/website title
- [ ] Abstract
- [ ] Tags
- [ ] Ordered by most recently added material if possible (I think this the default anyway)
- [x] Review the number of items pulled in - do we want more? The app seems to cope with large amounts of text so we could try 100 items?

Less useful fields: stuff about the publication itself rather than the topic of the publication e.g. article publication date, author, place of publication. Journal name might be useful, depending on discipline, but can go into wishlist if necessary.
# OAuth
- [x] Process of logging in work and returns the right data to the Moustache app
# Help text

Goal: text on process pages explains how and why to log in, in chatty, down-to-earth language (no jargon or tech language)
- [ ] Review Jack's documentation against current process and tone style
- [ ] Incorporate Jack's documentation into the process pages
## Target fields from user profile (probably wishlist or fallback stuff)
- [ ] Disciplines?
## Target fields from item

Maybe in future we'll pull in the item abstract and tags
- [x] Add this to future wish list
