### ISSUE TITLE
General thoughts for design tweaks

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#109]
- [x] remove the 'go to top' button from secondary content pages
- [x] Tighten up the spacing between the text box and the 'make some magic' button so the relationship is really clear - at the moment the button is closer to the footer than the text box. See #143  
- [ ] Introduce some separation between the 'Go home and feed the machine new text!' and 'Like what you see? Save these results (will open on another page)' texts, as it looks like a paragraph and header rather than two separate actions. See #143 
- [ ] On a small screen that shows only the logo and three steps, there's no indication that there's more below. (And we have two pieces of anecdotal evidence via reports from friends that people thought that was the whole page). We could tighten up the whitespace so the call-to-action text is more likely to be visible, or use a design element to direct attention down. Thoughts? See https://github.com/chnm/serendipomatic/issues/119
