### ISSUE TITLE
Serendipity machine: from input text parsing to query terms Do list

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#12]
- [x] Get basic input form parsing working
- [x] Get text tokens from unstructured text
- [x] Choose entity recognition service
- [x] Document entity recognition service decision
- [ ] Hook recognised entities into API search fields
- keywords - unspecified search (i.e. all fields)
- people/organisations -> OR in creator, subject, description, title (?)
- dates -> DPLA temporal. Europeana?
- spatial -> DPLA spatial. Europeana?
- [x] Randomise which candidate terms go into the search query so search results will be slightly different each time
- [x] Optimise the query terms for optimum results - enough noise/randomness but also recognisably based on the queries submitted. 
- [ ] Consider whether need to tweak based on the number of terms or size of resultset (if too large or too small)
- [x] Bring Zotero data input into the code flow
