### ISSUE TITLE
Design look and feel, UX guidelines, site-wide items

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#13]
Logo, microcopy, etc.
- [x] 1-2-3 step glyphs
- [x] Logo and strapline design
- [x] Logo and strapline design variations - stacked, mini, favicon, whatever
- [x] Colour scheme
- [x] CSS grid
- [x] Nav menu
- [x] Page footer
- [x] error pages for 404/500
- [ ] styling for error messages, e.g. no input on the  form
- [x] set up Google Analytics account
- [x] Add Google Analytics code to base template
- [x] Update Analytics profile with final main URL when decided
### Google Analytics code for base template

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42903011-1', 'serendipomatic.com');
  ga('send', 'pageview');

</script>
```
