### ISSUE TITLE
lead minutes

### ISSUE THREAD

**Issue by mfrazer** [chnm/serendipomatic#138]
What follows are minutes from the voice call that Meghan, Mia, Jack, and Brian had on 12 August. We're planning another call for next week sometime. We will keep these minutes open until that next meeting and invite the whole team to comment on them.

<DRAFT>
Need to establish a roadmap, but we're still in crunch mode, so in the meantime, want to set forth some guidelines for how the whole team can most productively behave in the meantime:
- Assume action is better than inaction (in response to suggestion that some of us weren't sure if we should jump in)
- Search existing issues before adding a new one in case it's already in the list
- If you enter an issue, assign it to the most logical person. If you are assigned an issue, but can't work on it, assign it to the next most logical person or one of the leads. 
- If you are working on an issue, assign it to yourself, so everyone knows who's working on what and so we don't duplicate effort.
-  When you commit, please include the related issue number using the built-in GitHub syntax for linking commits to issues
- If you're the one who solved an issue (added the code, text, whatever) you should _not_ be the one who closes the issue
- In the spirit of the Collaborator's Bill of Rights (http://mith.umd.edu/offthetracks/recommendations/) all of the OWOT team members should feel empowered to write/blog/present, etc, about the project as well as take credit for the work that they have done. We have created an issue (#116) to track conferences so that we don't duplicate proposals.

When deciding if a commit is ready to go to production, we would like to consider:
- are we staying true to the original vision / tone of Serendip-o-matic?
- are the design elements in line with pre-existing content?
- have any recent changes affected the accessibility of the site?
- a code review and reality-check functionality against the original vision - serendipity over utility

We are still hammering out how to implement a sign-off process for pushing to live, but for now, use the "Please review this on dev for going live to prod" label to indicate that you have something ready to go so others can take a look and sign off.

Next month's priorities:
- [ ] more automated deploy process, @briancroxall is going to facilitate this, working with @rlskoeser and @rsanc77 and other CHNM staff
- [ ] add text to Connect page regarding new inclusion of additional APIs - Brian
- [ ] write -one-page document 'go live' checklist (started at https://github.com/chnm/serendipomatic/wiki/Serendip-o-matic-%27go-live%27-checklist )
- [ ] development priorities ( - more detail at https://github.com/chnm/serendipomatic/wiki/Wishlist-items-and-future-development-road-map#development-roadmap-up-to-the-end-of-summer-re-announcement
  - Zotero integration
    - Getting "save to" ironed out
    - Getting more of the library pulled into Serendip-o-matic or updating what we promise in text
  - masonry issues
  - adding masonry 're-arrange results' shuffle) - Mia
- [ ] outreach priorities (promote CafePress, Zotero list, bookmarks) - Jack
- [ ] add licenses information in additional places - Meghan
- [ ] additional writing/promotional opportunities - Meghan
- [ ] documentation - All
- [ ] roadmap - PMs/Leads

Brian is going to set up another call for the four of us.  Feel free to comment here or just get in touch with us if you have questions or issues.
@rpalin @fontnerd @JackDougherty @amrys @mfrazer @erose @scottkleinman @moltude  @amandavisconti @mialondon @foundhistory
