### ISSUE TITLE
Serendipity machine results filtering

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#3]
Tasks related to improving the filtering of results back from the API queries
- [ ] Filter out results without images (ideally at query level)
- [ ] De-dupe query results for e.g. related editions or copies of an item
- [ ] Microcopy for results screen if no search results
- [ ] Microcopy for results screen if not many results (probably for wishlist)
