### ISSUE TITLE
Onboarding UX/input screen

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#4]
- [x] Front page should orient user to the scope and main function of the site
- [x] Page and form layout should orient user to the main call to action - load in some text and see what we give you back
- [x] Include link to Wikipedia Featured Article for people whose minds go blank when asked to think of some text to use
- [ ] Integrate the 'Zotero user? Try this' call to action with appropriate weight for a) first time b) second time users
- [x] Deal with the complication of Zotero OAuth UX
- [x] Add JavaScript to remove the text when you click into the input text box
