### ISSUE TITLE
QA on user stories - overview for keeping track of tests

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#5]
# Data input
- [ ] A user can paste text into a search box to initiate a search so they can find objects related to the text
- [ ] A user can submit their entire Zotero library as the input for a search so they can get search results related to the objects already in their collection
- [ ] A user can submit a single Zotero collection (“folder”) from their library as the input for a search so they can get search results related to the objects already in their collection
- [ ] A user can submit structured data (e.g., csv, json) into the input box and have results returned (input treated as any other text, no structure used)
- [ ] A user can submit a URL to the input box and have resulted returned (page scraped for terms, no structure or only very basic semantic markup used - H1 etc)
- [ ] A user can submit a Wikipedia URL to the input box and have resulted returned (page scraped for structured data terms or terms pulled from DBpedia)
- [ ] Test to see what happens when content that includes unicode characters is used
- [ ] Is the search doing ok with non-English language stuff? (not detecting language yet)
- [x] What happens if a user doesn't enter any text?
# Serendipity machine
- [ ] Reloading the page gives (slightly) different search results
# Delightful results page
- [ ] check accessibility of results page (when all JavaScript and CSS libraries put in)
- [ ] check responsiveness of results page (target iPhone/nearest available Android phone first then tablets)
- [ ] check results page with touch devices
- [ ] When viewing search results, a user can click on a result so they can read more information about the specific object
- [ ] When presented with search results, a user can “re-order” those specific results and see them in a different order so they can see things in new relationships to one another
- [ ] When presented with search results, a user can “re-search” to run the same search query and be presented with different search results so they can see new objects that are serendipitously related to their query
- [ ]  For the above two items, also check https://github.com/chnm/petulant-adventure/issues/29
- [x] A user can enter a search term and get results from DPLA, Europeana and Flickr Commons e.g. https://www.flickr.com/photos/anmm_thecommons/7332270140/ doesn't currently trigger any Commons results
# General
- [ ] What happens if a user goes to a page that doesn't exist?
