### ISSUE TITLE
Wishlist items - items for post-launch and/or possible future development

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#6]
- [ ] Create a Serendip-o-matic Zotero library that could act as the seed for queries from people who don't have one.
- [ ] Set up link tagging on Google Analytics to track e.g. how many people go back to the input screen to run a second query and how many people click on links to sources https://support.google.com/analytics/answer/2558867?hl=en&utm_id=ad
- [ ] Now that the project is named and has URLs etc we should re-apply for all the API keys and update them in the config
- [ ] Implement the 'rearrange' functionality with backend fields that work as expected (ie right quality stuff in the right fields)
- [ ] Use Europeana 'completeness' score in query if not already
- [ ] Improve randomness of query term combination - Scott W has ideas for this
