### ISSUE TITLE
Wishlist items - items for inclusion now if possible

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#7]
# UX
- [ ] Can users who've already done the input process once see a slightly different front page/input screen that emphasises using Zotero (with enough context to explain what it is)
- [ ] Can we crop images to interesting detail / faces?
- [ ] Can we use an item from your results as the seed for the next query?
- [ ] Can you 'tweet your seed' item?
- [ ] Can we zoom in to a closer view of documents in the thumbnails to make them more interesting and give a better sense of the document e.g. 
  ![sample_documentview_screenshot](https://f.cloud.github.com/assets/380763/889667/4b8a701c-fa23-11e2-876b-4eb741bc7f0c.png)
# APIs to integrate
- [x] 1 DPLA
- [x] 2 Europeana
- [x] 3 Flickr Commons 
- [x] 4 Trove/DigitalNZ
- [ ] 5 Somewhere in Asia, Middle East?

Possibly also BHL (biodiversity), Pelagios - subject specialist APIs
