### ISSUE TITLE
Delightful results screen To Do list

### ISSUE THREAD

**Issue by mialondon** [chnm/serendipomatic#8]
# Bugs/annoyances to fix
- [x] check dates on search term results -- not available or not getting passed thru to item? https://github.com/chnm/petulant-adventure/issues/25
- [x] adjust handoff between input and stash display to allow reload to vary results: store all keywords/terms in session, and then filter/select in the view (filed by Rebecca) https://github.com/chnm/petulant-adventure/issues/26
- [x] redirect to home page if stash url is loaded with no data in the session (?) (filed by Rebecca) https://github.com/chnm/petulant-adventure/issues/27
## Items to include on results page
- [x] user's query terms
- [x] list the sources used with links to search their catalogues directly - either document how to update this or write from a list of APIs held centrally somewhere https://github.com/chnm/petulant-adventure/issues/28
- [x]  'save the links from this page' function
- [x] Masonry works ok with variable image sizes https://github.com/chnm/petulant-adventure/issues/30
- [x] Each result includes: title, creator, date, link to source (with source name as link text). [May change depending on what we get back from APIs and need for good UX] https://github.com/chnm/petulant-adventure/issues/31
# Design issues to solve
- [x] What kind of GUI item to tempt people into flipping over the cards? https://github.com/chnm/petulant-adventure/issues/33
- [x] Click or hover to flip cards? And what to click on to go to original link and how to flip card over again? https://github.com/chnm/petulant-adventure/issues/16 was the placeholder for this, though the original text seems to have changed
